on: push

name: Test Find Issue Key

jobs:
  test-find-issue-key:
    name: Find Issue Key
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Find Issue Key
      uses: ./
      with:
        from: commits

    - name: Find Issue Key
      id: find
      uses: ./
      with:
        string: Search is performed in this string. FIND-1 will be found

    - name: Find Issue Key
      uses: ./
      with:
        string: ${{ github.event.ref }} will search in branch name

    - name: error if missing issue
      if: ${{ steps.find.outputs.issue == '' }}
      run: echo "Issue not found" && exit 1

    - name: Find issue info
      run: echo "Issue ${{ steps.find.outputs.issue }} was found"
